#pragma once

#include <stdlib.h>

#include "includes/coff/image.hpp"
#include "includes/nt/image.hpp"

#define false 0
#define true 1

typedef	unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;

// WINDOWS PE STRUCT DEFINITIONS SO I DONT NEED TO INCLUDE WINDOWS LIB

#define chk_IMAGE_NT_OPTIONAL_HDR32_MAGIC       0x10b
#define chk_IMAGE_NT_OPTIONAL_HDR64_MAGIC       0x20b
#define chk_IMAGE_NUMBEROF_DIRECTORY_ENTRIES    16
#define chk_IMAGE_DOS_SIGNATURE                 0x5A4D

#define chk_IMAGE_DIRECTORY_ENTRY_EXPORT          0
#define chk_IMAGE_DIRECTORY_ENTRY_IMPORT          1
#define chk_IMAGE_DIRECTORY_ENTRY_RESOURCE        2
#define chk_IMAGE_DIRECTORY_ENTRY_EXCEPTION       3
#define chk_IMAGE_DIRECTORY_ENTRY_SECURITY        4
#define chk_IMAGE_DIRECTORY_ENTRY_BASERELOC       5
#define chk_IMAGE_DIRECTORY_ENTRY_DEBUG           6
#define chk_IMAGE_DIRECTORY_ENTRY_ARCHITECTURE    7
#define chk_IMAGE_DIRECTORY_ENTRY_GLOBALPTR       8
#define chk_IMAGE_DIRECTORY_ENTRY_TLS             9
#define chk_IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG    10
#define chk_IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT   11
#define chk_IMAGE_DIRECTORY_ENTRY_IAT            12
#define chk_IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT   13
#define chk_IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR 14

#define IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA 0x0020
#define IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE 0x0040
#define IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY 0x0080
#define IMAGE_DLLCHARACTERISTICS_NX_COMPAT 0x0100
#define IMAGE_DLLCHARACTERISTICS_NO_ISOLATION 0x0200
#define IMAGE_DLLCHARACTERISTICS_NO_SEH 0x0400
#define IMAGE_DLLCHARACTERISTICS_NO_BIND 0x0800
#define IMAGE_DLLCHcARACTERISTICS_APPCONTAINER 0x1000
#define IMAGE_DLLCHARACTERISTICS_WDM_DRIVER 0x2000
#define IMAGE_DLLCHARACTERISTICS_GUARD_CF 0x4000
#define IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE 0x8000

void checkpe(FILE *);